### ISSUE TITLE
404 on whitebox 1.2.0 import

### ISSUE THREAD

**Issue by agumartina** [NCAR/wrf_hydro_gis_preprocessor#5]
Hey guys, I had a 404 on import _from whitebox.WBT.whitebox_tools import WhiteboxTools_ (line 54, wrfhydro_functions.py).
It looks like an outdated url.
an update of whitebox to the latest (1.4.0) fixed the issue
So i recommend to update package recommendations to whitebox 1.4.0.

thank you

agu

**Comment by kmsampson** [comment]
Agu,

Thank you for the recommendation. I updated the Whitebox version in the `README.md` file as well as the `requirements.txt`.
